<?xml version="1.0" encoding="utf-8"?><Database Name="BibliotecaMarie" Class="BibliotecaMarieDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=EDSERVER;Initial Catalog=BibliotecaMarie;User ID=admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BibliotecaMarieConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Customer_Item_Cliente" Member="Item_Clientes" ThisKey="IdCliente" OtherKey="IdCliente" Type="Item_Cliente" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="IdStatus" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Member="Status1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Status_Item" Member="Items" ThisKey="IdStatus" OtherKey="IdStatus" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Item_Cliente" Member="Item_Clientes">
    <Type Name="Item_Cliente">
      <Column Name="IdItem" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Customer_Item_Cliente" Member="Customer" ThisKey="IdCliente" OtherKey="IdCliente" Type="Customer" IsForeignKey="true" />
      <Association Name="Item_Item_Cliente" Member="Item" ThisKey="IdItem" OtherKey="Id" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Type" Member="Types">
    <Type Name="Type">
      <Column Name="IdType" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Member="Type1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Type_Item" Member="Items" ThisKey="IdType" OtherKey="IdType" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdLanguage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Item_Item_Cliente" Member="Item_Clientes" ThisKey="Id" OtherKey="IdItem" Type="Item_Cliente" />
      <Association Name="Status_Item" Member="Status" ThisKey="IdStatus" OtherKey="IdStatus" Type="Status" IsForeignKey="true" />
      <Association Name="Type_Item" Member="Type" ThisKey="IdType" OtherKey="IdType" Type="Type" IsForeignKey="true" />
      <Association Name="Language_Item" Member="Language" ThisKey="IdLanguage" OtherKey="IdLanguage" Type="Language" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Language" Member="Languages">
    <Type Name="Language">
      <Column Name="IdLanguage" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Language" Member="Language1" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Language_Item" Member="Items" ThisKey="IdLanguage" OtherKey="IdLanguage" Type="Item" />
    </Type>
  </Table>
</Database>